;;; yunge-dired-test.el --- Dired tests -*- lexical-binding: t; -*-
;; SPDX-FileCopyrightText: 2026 Chen Zhexuan
;; SPDX-License-Identifier: MIT

(require 'yunge-test-helper)

(declare-function dired-do-copy "dired-aux" (&optional arg))
(declare-function dired-goto-file "dired" (file))
(declare-function dired-mark "dired" (arg &optional interactive))
(declare-function dired-dwim-target-directory "dired-aux")
(declare-function evil-ex-execute "evil-ex" (string))
(declare-function project-known-project-roots "project")
(declare-function yunge-dired--remember-project "yunge-dired")

(defvar dired-do-revert-buffer)
(defvar dired-movement-style)
(defvar ls-lisp-filesize-d-fmt)
(defvar ls-lisp-uid-s-fmt)
(defvar project--list)
(defvar project-list-file)

(yunge-test-deftest-lazy-load yunge-dired
  (dired evil project wdired which-key))

(ert-deftest yunge-dired-copy-commands-select-path-kinds ()
  (require 'yunge-dired)
  (yunge-test-enable-evil)
  (let* ((root (make-temp-file "yunge-dired-copy-" t))
         (directory (expand-file-name "notes/" root))
         (first (expand-file-name "alpha.txt" directory))
         (second (expand-file-name "beta space.txt" directory))
         (kill-ring nil)
         (kill-ring-yank-pointer nil)
         (interprogram-cut-function nil)
         (interprogram-paste-function nil)
         (last-command nil)
         buffer)
    (make-directory (expand-file-name ".git/" root))
    (make-directory directory)
    (unwind-protect
        (save-window-excursion
          (with-temp-file first (insert "alpha\n"))
          (with-temp-file second (insert "beta\n"))
          (setq buffer (dired-noselect directory))
          (switch-to-buffer buffer)
          (dired-goto-file first)
          (call-interactively (key-binding (kbd "y f")))
          (should (equal (car kill-ring) "alpha.txt"))
          (call-interactively (key-binding (kbd "y p")))
          (should (equal (car kill-ring) first))
          (call-interactively (key-binding (kbd "y P")))
          (should (equal (car kill-ring) "notes/alpha.txt"))
          (dired-mark 1)
          (dired-goto-file second)
          (dired-mark 1)
          (call-interactively (key-binding (kbd "y f")))
          (should (equal (car kill-ring) "alpha.txt \"beta space.txt\"")))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-directory root t))))

(ert-deftest yunge-dired-isolates-ls-lisp-widths-when-copying ()
  (require 'yunge-dired)
  (require 'dired)
  (require 'dired-aux)
  (let* ((root (make-temp-file "yunge-dired-add-" t))
         (source-directory (expand-file-name "source/" root))
         (target-directory (expand-file-name "target/" root))
         (source (expand-file-name "copied.txt" source-directory))
         (target (expand-file-name "copied.txt" target-directory))
         (existing (expand-file-name "existing.txt" target-directory))
         source-buffer target-buffer)
    (make-directory source-directory)
    (make-directory target-directory)
    (write-region "copied" nil source nil 'silent)
    (write-region "existing" nil existing nil 'silent)
    (setq source-buffer (dired-noselect source-directory)
          target-buffer (dired-noselect target-directory))
    (unwind-protect
        (with-current-buffer source-buffer
          ;; Reproduce a source listing whose owner and size columns are much
          ;; wider than the destination listing's columns.
          (setq ls-lisp-uid-s-fmt " %-19s"
                ls-lisp-filesize-d-fmt " %20d")
          (should (dired-goto-file source))
          (let ((dired-do-revert-buffer nil))
            (cl-letf (((symbol-function 'dired-mark-read-file-name)
                       (lambda (&rest _arguments) target-directory)))
              (dired-do-copy)))
          (with-current-buffer target-buffer
            (should (dired-goto-file target))
            (should (eq (char-after (line-beginning-position)) ?C))
            (let ((target-column (current-column)))
              (should (dired-goto-file existing))
              (should (= (current-column) target-column)))))
      (dolist (buffer (list source-buffer target-buffer))
        (when (buffer-live-p buffer)
          (kill-buffer buffer)))
      (delete-directory root t))))

(ert-deftest yunge-dired-binds-keys ()
  (require 'yunge-dired)
  (yunge-test-enable-evil)
  (require 'which-key)
  (require 'dired)

  ;; Key resolution uses synthetic Dired buffers and must not persist them.
  (cl-letf (((symbol-function 'yunge-dired--remember-project) #'ignore))
    (yunge-test-evil-normal-keys
     'dired-mode
     '(("RET" . dired-find-file)
       ("M-h" . dired-up-directory)
       ("i" . dired-toggle-read-only)
       ("j" . dired-next-line)
       ("k" . dired-previous-line)
       ("m" . dired-mark)
       ("d" . dired-flag-file-deletion)
       ("u" . dired-unmark)
       ("x" . dired-do-flagged-delete)
       ("t" . evil-find-char-to)
       ("* t" . dired-toggle-marks)
       ("% r" . dired-do-rename-regexp)
       ("w" . evil-forward-word-begin)
       ("y f" . yunge-dired-copy-filename)
       ("y p" . yunge-dired-copy-absolute-path)
       ("y P" . yunge-dired-copy-project-path)
       ("SPC m a m" . dired-do-chmod)
       ("SPC m e" . yunge-dired-open-directory-externally)
       ("SPC m h" . dired-summary)
       ("SPC m l s" . dired-do-symlink)
       ("SPC m r" . yunge-dired-reveal-in-file-manager)))

    (yunge-test-evil-visual-keys
     'dired-mode
     '(("m" . dired-mark)
       ("d" . dired-flag-file-deletion)
       ("u" . dired-unmark)
       ("t" . evil-find-char-to)
       ("* t" . dired-toggle-marks)
       ("% m" . dired-mark-files-regexp)
       ("y" . evil-yank)))

    (should (eq dired-movement-style 'bounded-files))))

(ert-deftest yunge-dired-opens-current-directory-externally ()
  (require 'yunge-dired)
  (let ((default-directory "C:/project/")
        opened-files)
    (cl-letf (((symbol-function 'shell-command-do-open)
               (lambda (files)
                 (setq opened-files files))))
      (call-interactively #'yunge-dired-open-directory-externally))
    (should (equal opened-files (list default-directory)))))

(ert-deftest yunge-dired-reveal-selects-marked-files-or-file-at-point ()
  (require 'yunge-dired)
  (yunge-test-enable-evil)
  (let* ((directory (make-temp-file "yunge-dired-reveal-" t))
         (first (expand-file-name "first file.txt" directory))
         (second (expand-file-name "second's 测试.txt" directory))
         (third (expand-file-name "third.txt" directory))
         (yunge-config-directory
          (file-name-as-directory (expand-file-name "Config Dir" directory)))
         (script (expand-file-name "script/yunge-reveal.ps1"
                                   yunge-config-directory))
         (system-type 'windows-nt)
         (powershell "pwsh")
         buffer arguments)
    (unwind-protect
        (save-window-excursion
          (dolist (file (list first second third))
            (write-region "" nil file nil 'silent))
          (setq buffer (dired-noselect directory))
          (switch-to-buffer buffer)
          (cl-letf (((symbol-function 'executable-find)
                     (lambda (_program) powershell))
                    ((symbol-function 'w32-shell-execute)
                     (lambda (&rest args) (setq arguments args))))
            (dired-goto-file third)
            (call-interactively (key-binding (kbd "SPC m r")))
            (should (equal arguments
                           (list "open" "explorer.exe"
                                 (format "/select,\"%s\""
                                         (subst-char-in-string ?/ ?\\ third)))))

            (dired-goto-file first)
            (dired-mark 1)
            (dired-goto-file second)
            (dired-mark 1)
            (dired-goto-file third)
            (call-interactively (key-binding (kbd "SPC m r")))
            (pcase-let* ((`("open" "pwsh" ,parameters 0) arguments)
                         (encoded (car (last (split-string parameters))))
                         (command
                          (decode-coding-string
                           (base64-decode-string encoded) 'utf-16le)))
              (should (equal command
                             (concat "& '" script "' '" first "' '"
                                     (file-name-directory second)
                                     "second''s 测试.txt'"))))

            (setq powershell nil)
            (call-interactively (key-binding (kbd "SPC m r")))
            (should (equal arguments
                           (list "open" "explorer.exe"
                                 (format "/select,\"%s\""
                                         (subst-char-in-string ?/ ?\\ first)))))))
      (when (buffer-live-p buffer)
        (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest yunge-dired-drop-transfers-a-batch-to-the-target-window ()
  (require 'yunge-dired)
  (require 'dnd)
  (let* ((root (make-temp-file "yunge-dired-drop-" t))
         (source-directory (expand-file-name "source/" root))
         (target-directory (expand-file-name "target/" root))
         (names '("one.txt" "two.txt"))
         (uris (mapcar (lambda (name)
                         (concat "file:" (expand-file-name name source-directory)))
                       names))
         source-buffer target-buffer menu-action)
    (make-directory source-directory)
    (make-directory target-directory)
    (unwind-protect
        (save-window-excursion
          (dolist (name names)
            (with-temp-file (expand-file-name name source-directory)
              (insert name " contents\n")))
          (setq source-buffer (dired-noselect source-directory)
                target-buffer (dired-noselect target-directory))
          (switch-to-buffer source-buffer)
          (let ((source-window (selected-window))
                (target-window (split-window-right)))
            (set-window-buffer target-window target-buffer)
            (cl-letf (((symbol-function 'x-popup-menu)
                       (lambda (&rest _) menu-action)))
              (setq menu-action nil)
              (dnd-handle-multiple-urls target-window (copy-sequence uris) 'move)
              (dolist (name names)
                (should (file-exists-p (expand-file-name name source-directory)))
                (should-not (file-exists-p (expand-file-name name target-directory))))

              (setq menu-action 'copy)
              (should (eq (dnd-handle-multiple-urls
                           target-window (copy-sequence uris) 'move)
                          'copy))
              (should (eq (selected-window) source-window))
              (dolist (name names)
                (let ((target (expand-file-name name target-directory)))
                  (should (file-exists-p (expand-file-name name source-directory)))
                  (with-temp-buffer
                    (insert-file-contents target)
                    (should (equal (buffer-string)
                                   (concat name " contents\n"))))))

              (dolist (name names)
                (delete-file (expand-file-name name target-directory)))
              (setq menu-action 'move)
              (should (eq (dnd-handle-multiple-urls
                           target-window (copy-sequence uris) 'copy)
                          'move))
              (dolist (name names)
                (should-not (file-exists-p (expand-file-name name source-directory)))
                (with-temp-buffer
                  (insert-file-contents (expand-file-name name target-directory))
                  (should (equal (buffer-string)
                                 (concat name " contents\n"))))))))
      (dolist (buffer (list source-buffer target-buffer))
        (when (buffer-live-p buffer) (kill-buffer buffer)))
      (delete-directory root t))))

(ert-deftest yunge-dired-drop-opens-a-file-in-the-target-window ()
  (require 'yunge-dired)
  (require 'dnd)
  (let* ((root (make-temp-file "yunge-dired-open-" t))
         (target-directory (expand-file-name "target/" root))
         (file (expand-file-name "opened.txt" root))
         source-buffer target-buffer)
    (make-directory target-directory)
    (unwind-protect
        (save-window-excursion
          (with-temp-file file (insert "opened contents\n"))
          (setq source-buffer (dired-noselect root)
                target-buffer (dired-noselect target-directory))
          (switch-to-buffer source-buffer)
          (let ((source-window (selected-window))
                (target-window (split-window-right))
                (dnd-open-file-other-window nil))
            (set-window-buffer target-window target-buffer)
            (cl-letf (((symbol-function 'x-popup-menu)
                       (lambda (&rest _) 'open)))
              (should (eq (dnd-handle-multiple-urls
                           target-window (list (concat "file:" file)) 'copy)
                          'private)))
            (should (eq (selected-window) source-window))
            (should (eq (window-buffer target-window) (get-file-buffer file)))
            (with-current-buffer (window-buffer target-window)
              (should (equal (buffer-string) "opened contents\n")))))
      (dolist (buffer (list source-buffer target-buffer (get-file-buffer file)))
        (when (buffer-live-p buffer) (kill-buffer buffer)))
      (delete-directory root t))))

(ert-deftest yunge-dired-remembers-projects-but-not-ordinary-directories ()
  (require 'yunge-dired)
  (require 'dired)
  (let* ((root (make-temp-file "yunge-dired-project-" t))
         (directory (expand-file-name "src/" root))
         (plain-directory (make-temp-file "yunge-dired-plain-" t))
         (project-list-file (expand-file-name "projects.eld" root))
         (project--list 'unset)
         project-buffer plain-buffer known-roots)
    (make-directory (expand-file-name ".git/" root))
    (make-directory directory)
    (unwind-protect
        (progn
          (setq project-buffer (dired-noselect directory)
                known-roots (project-known-project-roots))
          (should (seq-some
                   (lambda (known-root)
                     (file-equal-p known-root root))
                   known-roots))
          (setq plain-buffer (dired-noselect plain-directory))
          (should (equal (project-known-project-roots) known-roots)))
      (dolist (buffer (list project-buffer plain-buffer))
        (when (buffer-live-p buffer) (kill-buffer buffer)))
      (delete-directory root t)
      (delete-directory plain-directory t))))

(ert-deftest yunge-dired-prefers-last-selected-target-window ()
  (require 'yunge-dired)
  (require 'dired)
  (let* ((root (make-temp-file "yunge-dired-target-" t))
         (source-directory (expand-file-name "source/" root))
         (older-directory (expand-file-name "older/" root))
         (target-directory (expand-file-name "target/" root))
         buffers)
    (dolist (directory
             (list source-directory older-directory target-directory))
      (make-directory directory))
    (unwind-protect
        (save-window-excursion
          (delete-other-windows)
          (let* ((source-window (selected-window))
                 (older-window (split-window-right))
                 (target-window
                  (split-window older-window nil 'below)))
            (dolist (entry
                     (list (cons source-window source-directory)
                           (cons older-window older-directory)
                           (cons target-window target-directory)))
              (let ((buffer (dired-noselect (cdr entry))))
                (push buffer buffers)
                (set-window-buffer (car entry) buffer)))
            (select-window older-window)
            (select-window target-window)
            (select-window source-window)
            (should
             (equal (dired-dwim-target-directory)
                    target-directory))))
      (dolist (buffer buffers)
        (when (buffer-live-p buffer)
          (kill-buffer buffer)))
      (delete-directory root t))))

(ert-deftest yunge-wdired-applies-or-discards-renames ()
  (require 'yunge-dired)
  (yunge-test-enable-evil)
  (dolist (finish '(t nil))
    (let* ((directory (make-temp-file "yunge-wdired-" t))
           (original (expand-file-name "old.txt" directory))
           (renamed (expand-file-name "new.txt" directory))
           buffer)
      (unwind-protect
          (save-window-excursion
            (with-temp-file original (insert "file contents\n"))
            (setq buffer (dired-noselect directory))
            (switch-to-buffer buffer)
            (dired-goto-file original)
            (call-interactively (key-binding (kbd "i")))
            (should (eq major-mode 'wdired-mode))
            (beginning-of-line)
            (search-forward "old.txt" (line-end-position))
            (replace-match "new.txt")
            (evil-normal-state)
            (if finish
                (call-interactively (key-binding (kbd "ZZ")))
              (evil-ex-execute "q"))
            (should (eq major-mode 'dired-mode))
            (should (eq (window-buffer (selected-window)) buffer))
            (should (file-exists-p (if finish renamed original)))
            (should-not (file-exists-p (if finish original renamed)))
            (with-temp-buffer
              (insert-file-contents (if finish renamed original))
              (should (equal (buffer-string) "file contents\n"))))
        (when (buffer-live-p buffer) (kill-buffer buffer))
        (delete-directory directory t)))))

;;; yunge-dired-test.el ends here
