;;; init.el --- Emacs configuration -*- lexical-binding: t; -*-
;; SPDX-FileCopyrightText: 2026 Chen Zhexuan
;; SPDX-License-Identifier: MIT

(require 'yunge-state)
(require 'yunge-autoload)
(yunge-autoload-load)
(require 'yunge-server)
(require 'yunge-history)
(require 'yunge-autorevert)
(require 'yunge-edit)
(require 'yunge-project)
(require 'yunge-treesit)
(require 'yunge-cc)
(when (eq system-type 'darwin)
  (require 'yunge-mac))
(require 'yunge-package)
(require 'yunge-theme)
(require 'yunge-evil)
(require 'yunge-eglot)
(require 'yunge-xref)
(require 'yunge-org)
(require 'yunge-fangcun)
(require 'yunge-expreg)
(require 'yunge-tab)
(require 'yunge-bookmark)
(require 'yunge-window)
(require 'yunge-which-key)
(require 'yunge-vertico)
(require 'yunge-orderless)
(require 'yunge-corfu)
(require 'yunge-slime)
(require 'yunge-marginalia)
(require 'yunge-avy)
(require 'yunge-consult)
(require 'yunge-embark)
(require 'yunge-magit)
(require 'yunge-ghostel)
(require 'yunge-elpaca)
(require 'yunge-dired)
(require 'yunge-help)

;; Load saved Custom state before command-line files are visited.
(load custom-file 'noerror 'nomessage)

;;; init.el ends here
